[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist"

# Force new deployment - timestamp: 2025-01-05-06:54

[functions]
  external_node_modules = ["express", "cors", "dotenv", "serverless-http"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
