[build]
  command = "npm ci && npm run build:client"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
